num1=int(input("Enter First Number :"))
num2=int(input("Enter Second Number :"))
print("Addition :" , num1 + num2)
print("Subtraction :", num1 - num2 )
print("Multipication :", num1 * num2)
print("Division :", num1/num2)